# Generated by Django 5.1.2 on 2024-10-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(upload_to='media', verbose_name='logo')),
                ('company_name', models.CharField(max_length=30, verbose_name='about the page')),
                ('about_the_page', models.CharField(max_length=150, verbose_name='about the page')),
                ('img', models.ImageField(upload_to='media', verbose_name='page img')),
            ],
        ),
    ]
