# Generated by Django 5.1.2 on 2024-10-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_header_about_the_page_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about_company',
            new_name='H_about_company',
        ),
        migrations.RenameModel(
            old_name='Header',
            new_name='H_Header',
        ),
    ]
