# Generated by Django 5.1.2 on 2024-10-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_work'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
