# Generated by Django 5.1.2 on 2024-10-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=100, verbose_name='work name')),
                ('work_about', models.CharField(max_length=100, verbose_name='work about')),
                ('img', models.ImageField(upload_to='media', verbose_name='work img')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
            },
        ),
    ]
