# Generated by Django 5.1.2 on 2024-10-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_work_choice_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='choice_field',
            field=models.CharField(choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], default='left', max_length=20),
        ),
    ]
