# Generated by Django 5.1.2 on 2024-10-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_work_choice_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='A_About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
            ],
        ),
    ]
