# Generated by Django 5.1.2 on 2024-10-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_a_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A_About',
        ),
    ]
